name: Clone, Execute and Upload
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Execute command (batch)
        run: .\\setup.exe /download .\\配置.xml
        shell: cmd
      - name: Upload folder
        uses: actions/upload-artifact@v3
        with:
          name: output_folder_upload
          path: Office\
